version: '3.8'

services:

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - /mnt/backup/docker-volumes/wingo-mongodb:/data/db
    command: mongod --bind_ip 0.0.0.0
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  scraper:
    build: ./scraper
    depends_on:
      - mongodb
    restart: always
  trainer:
    build: ./trainer
    depends_on:
      - mongodb
    volumes:
      - ./models:/app/models
    restart: always

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - trainer
    volumes:
      - ./models:/app/models
    restart: always
  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always